Disable -Wunused-value for surfaceflinger
```
frameworks/native/services/surfaceflinger/Display/DisplayModeController.cpp:293:14: error: ignoring temporary created by a constructor declared with 'nodiscard' attribute [-Werror,-Wunused-value]
  293 |             (std::scoped_lock(displayPtr->desiredModeLock), displayPtr->desiredModeOpt)
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Change-Id: I5e84dbd628f5c03f5e325f5ccc5d365d2f40c9dd
Flag: EXEMPT b/369277774
Bug: b/369277774
(cherry picked from commit 4648b7e8b5fd81580c81ad3a24e13b26ea9c12d2)